services:
  kali:
    build:
      context: .
      dockerfile_inline: |
        FROM kalilinux/kali-rolling
        RUN apt-get update -yqq && apt-get install -y --no-install-recommends \
            build-essential iproute2 python3 python3-pip tcpdump ethtool nmap rtpflood traceroute && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
    tty: true
    volumes:
      - ./src:/app
